#----------------------------------------------------------------------
#                     Makefile to build libipmiredfish
#                 Copyright (c) 2018 American Megatrends Inc 
#-----------------------------------------------------------------------

#------- Comment/uncomment the following line to enable/disable debugging------
DEBUG 		= n
#------------------------------------------------------------------------------

#---------------------- Change according to your files ------------------------
LIBRARY_NAME	= libcJSON
SRC		= cJSON.c

CFLAGS += -I./

include ${TOOLDIR}/rules/Rules.make.libs
#------------------------------------------------------------------------------
