#------- Comment/uncomment the following line to enable/disable debugging---------
DEBUG 	= n

#---------------------- Change according to your files ----------------------------
SRC 	= mctp-i3c.c 			# Source File
TARGET 	= mctp-i3c				# Output file

CFLAGS += -I. 

include ${TOOLDIR}/rules/Rules.make.apps
#----------------------------------------------------------------------------------------

